spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Al-iary?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: kang165
    connection-test-query: SELECT NOW() FROM dual
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  spring:
    output:
      ansi:
        enabled: always

  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8080