#spring:
#  datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://Al-iary-database.cy9gdtygeuyw.us-east-1.rds.amazonaws.com:3306/itogether
#  username: root
#  password: kang165
#
#my.jwt.secretKey=PKuqug3YctsBr0Kv0DZeWcGstNRe9Vsc
#my.jwt.refreshKey=miuXdbBehAQwNZ5QGMk2ftRlHM3atoyG
#
#kakao.clientId=47ab909f259ea3b830cda220244509c2
#kakao.redirectUri=https://a60d-118-34-229-88.ngrok.io/oauth/kakao/callback
#kakao.reqTokenUrl=https://kauth.kakao.com/oauth/token
#kakao.reqUserDataUrl=https://kapi.kakao.com/v2/user/me